name: Caller-workflow
on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: environment
        
jobs:
  #Call-workflow-for-build:
    #uses: ./.github/workflows/Build-workflow.yml
    
  Call-workflow-for-deploy:
    
    #needs: Call-workflow-for-build
    #uses: ./.github/workflows/Deploy-workflow.yml
    uses: ./.github/workflows/Test1.yml
    with:
          environment: ${{ github.event.inputs.environment }}
    
 
  
