name: testing
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy (Dev or Prod)?'
        required: true
        type: string
      Filters:
        description: 'Choose the required component'
        required: true
        type: choice
        options:
          - com1
          - com2
          - com3
jobs:
  copy_files:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      components-info: ${{ steps.set-matrix.outputs.backend-components }}
      filteredData: ${{ steps.filter-step.outputs.filteredData }}  # Corrected output name
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        working-directory: ./job_dependencies
        run: |
          echo "backend-components=`perl -pe 's/\s+//g' job_dependencies.json`" >> $GITHUB_OUTPUT
          echo "$backend-components"
      - name: Filtering JSON data
        id: filter-step
        run: |
          chosencomponents="${{ github.event.inputs.Filters }}"
          filteredData=$(jq -c --arg chosenCom "$chosencomponents" '.[] | select(.name == $chosenCom)' job_dependencies/job_dependencies.json)
          echo "::set-output name=filteredData::$filteredData"  # Corrected output name

  Comparison:
    runs-on: ubuntu-latest
    needs: copy_files
    continue-on-error: true
    strategy:
      matrix:
        components: ${{ fromJSON(needs.copy_files.outputs.components-info) }}
        
    env:
      name: ${{ matrix.components.name }}
      version: ${{ matrix.components.version }}
      
      Test: ${{ steps.iteration.outputs.NewName}}
    steps:
      - name: checking matrix value
        run: |
          echo "$name"
          echo "$version"
      - name: Process filtered data
        run: |
          echo "Filtered Data: ${{ needs.copy_files.outputs.filteredData }}"  # Output the filtered data for verification
      - name: filtered data iteration
        run: |
          filteredData=$(echo '${{ needs.copy_files.outputs.filteredData }}' | jq -c '.')
          for data in $filteredData; do
            name1=$(echo $data | jq -r '.name')
            version1=$(echo $data | jq -r '.version')
            echo "NewName: $name1, NewVersion: $version1"
            # Add your comparison logic here
          done


