name: Userinput 

on:
  pull_request_target:
    branches:
      - main
      - merge2
    types: [opened]

jobs:
  check_pull_request_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Pull Request Title is Empty
        id: check_title
        run: echo "::set-output name=is_empty::${{ github.event.pull_request.title == '' }}"

      - name: Assign Default Value if Pull Request Title is Empty
        if: steps.check_title.outputs.is_empty == 'true'
        run: echo "Pull Request Title is empty. Assigning default value."
        env:
          DEFAULT_TITLE: 'Dev'

      - name: Use Pull Request Title
        run: echo "Pull Request Title:${{ steps.check_title.outputs.is_empty == 'true' && env.DEFAULT_TITLE || github.event.pull_request.title }}"
